In [2]:
import numpy as np


In [4]:
numpy_arr=np.array([2,3,5,7,11])
print(numpy_arr)
add=numpy_arr+1
print(add)
multi=numpy_arr*2
print(multi)
div=numpy_arr/3
print(div)

[ 2  3  5  7 11]
[ 3  4  6  8 12]
[ 4  6 10 14 22]
[0.66666667 1.         1.66666667 2.33333333 3.66666667]


In [8]:
arr=np.array([1,2,3,6,4,5])
arr_rev=arr[::-1]
print(arr_rev)

[5 4 6 3 2 1]


In [12]:
def most_frequent(arr):
    values,counts=np.unique(arr,return_counts=True)
    max_count=np.max(counts)
    most_frequent_value=values[np.argmax(counts)]
    indices=np.where(arr==most_frequent_value)[0]
    return most_frequent_value,indices
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
mf_x,indices_x=most_frequent(x)
mf_y,indices_y=most_frequent(y)
print(f'frequent value in x:{mf_x},Indices:{indices_x}')
print(f'frequent value in y:{mf_y},Indices:{indices_y}')

frequent value in x:1,Indices:[0 5 7 8 9]
frequent value in y:1,Indices:[0 1 2]


In [14]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print('Q3a:',arr[0,1])
print('Q3b:',arr[2,0])

Q3a: 20
Q3b: 70


In [18]:
Yash=np.linspace(10, 100, 25)
print(Yash)
print(f'Array: {Yash}')
print(f'Dimensions: {Yash.ndim}')
print(f'Shape: {Yash.shape}')
print(f'Total elements: {Yash.size}')
print(f'Data type: {Yash.dtype}')
print(f'Total bytes: {Yash.nbytes}')
print('Transpose of the array :',Yash.reshape(len(Yash),1))
print('Transpose of the array :',Yash.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose of the array : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose of the array : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [20]:
ucs420_Yash=np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:",np.mean(ucs420_Yash))
print("Median:",np.median(ucs420_Yash))
print("Max:",np.max(ucs420_Yash))
print("Min:",np.min(ucs420_Yash))
print("Unique Elements:",np.unique(ucs420_Yash))
reshaped_ucs420_Yash=ucs420_Yash.reshape(4,3)
print("Reshaped:\n",reshaped_ucs420_Yash)
resized_ucs420_Yash=np.resize(ucs420_Yash,(2,3))
print("Resized:\n",resized_ucs420_Yash)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
 [[10 20 30]
 [40 50 60]]
